- client/scripts/videoPlayerButtons.js
- client/styles/trimVideo.css
Trim Video slider works now with Firefox, before WebKit supported browsers only
Microsoft Edge - Dose not work yet - CSS Problem
> Firefox: Trim Video slider now works

- README.md
- client/scripts/basics.js
- client/scripts/currentVideoDownloads.js
- client/scripts/index.js
- client/scripts/videoPlayerButtons.js
- client/styles/index.css
- client/styles/notify.css
- package-lock.json
- package.json
- server.js
- streamVideo.js
Allows a user to upload a video from there own devices to the server which then gets download to be turned into a video/mp4 file and creates thumbnails for it. Once the process is completed the video gets publish for the user to access at /saved/videos.
(There is no upload % to state how much % is needed to finish uploading the selected video, but as of now the system work and is stable to be used, the feature can be added on a late date)
> Video uploader

- README.md
- client/scripts/basics.js
- client/scripts/showAvailableVideos.js
- client/styles/index.css
- client/styles/searchBar.css
- server.js
search bar implementation that filters available videos by video title
> Search bar

- README.md
- client/scripts/currentVideoDownloads.js
- client/scripts/index.js
- client/scripts/showAvailableVideos.js
- client/styles/current-downloads.css
- data/user-settings.json
- server.js
- streamVideo.js
Implementation of compression_VP9 function.
Optional VP9 Compression at downloadVideoStream, downloadVideo, trimVideo, downloadUploadedVideo when values are set as true at user-settings.json (true by default) 006e989.
Check for available unfinished video downloads supports VP9 video download. 
Delete all video data: redesign.
Code improvements.
Updated README.
> VP9 video compression: H.264 video/mp4 -> VP9 video/webm

- __tests__/backend/streamVideo.test.js
- __tests__/client/basics.test.js
- __tests__/client/showAvailableVideos.test.js
- client/scripts/basics.js
- client/scripts/showAvailableVideos.js
- client/styles/index.css
- client/styles/showAvailableVideos.css
- client/styles/video-edit-settings.css
- server.js
- streamVideo.js
drag and drop functionalities to organize downloaded videos
> Drag drop displayed videos 

- backend/setup/create-json-data.js
- client/scripts/currentVideoDownloads.js
- client/scripts/optionMenu.js
- client/scripts/videoPlayerButtons.js
- client/styles/video-folder-edit-settings.css
- server.js
confirm the confirmation for a different confirmation layout to confirm if users want to confirm specified task
> Download confirmation redesign

- Dockerfile
- README.md
- backend/scripts/ffmpeg-path.js
- package-lock.json
- package.json
> Npm ffmpeg

- client/scripts/showAvailableVideos.js
add preventDefault & stopPropagation to drag event
Closes #71
> fix: prevent redirect on dropping element

- client/scripts/currentVideoDownloads.js
- client/styles/current-downloads.css
When untrunc isn't installed, video failed downloading
Option 1:  Restore damaged video - greyed out button - onclick display error: Untrunc Unavailable
Option 2: Delete Video Data
> currentVideoDownloads: Untrunc Unavailable Button

- __tests__/backend/scripts/available-videos.test.js
- __tests__/backend/scripts/check-path-validity.test.js
- backend/scripts/available-videos.js
- backend/scripts/check-path-validity.js
- backend/scripts/current-download-videos.js
- backend/scripts/data-videos.js
- backend/scripts/user-settings.js
Move function update_json_path_validity into check-path-validity.js as its repeated 4 JS files (user-settings, data-videos, current-download-videos, available-videos), easier to maintain
> Check path validity

- __tests__/backend/scripts/available-videos.test.js
- __tests__/backend/scripts/current-download-videos.test.js
- backend/scripts/available-videos.js
- backend/scripts/current-download-videos.js
current-download-videos.js code tested
6 function - 24 test cases
`npm test current-download-videos`
#54
> Unit Test current-download-videos.js

- __tests__/backend/scripts/data-videos.test.js
- backend/scripts/data-videos.js
data-videos.js code tested
6 function - 24 test cases
`npm test data-videos `
#54
> Unit Test data-videos.js

- __tests__/backend/scripts/ffmpeg-path.test.js
- backend/scripts/ffmpeg-path.js
ffmpeg-path.js code tested
11 function - 42 test cases
`npm test ffmpeg-path`  
#54
> Unit Test ffmpeg-path.js

- __tests__/backend/scripts/user-settings.test.js
- backend/scripts/available-videos.js
- backend/scripts/current-download-videos.js
- backend/scripts/data-videos.js
- backend/scripts/user-settings.js
user-settings.js code tested
7 function - 42 test cases
`npm test user-settings`  
#54
> Unit Test user-settings.js

- backend/scripts/delete-data.js
> Folder Deletion Bug - Fix #81

- __tests__/backend/scripts/ffmpeg-download-trimed-video.test.js
- backend/scripts/ffmpeg-download-trimed-video.js
- server.js
ffmpeg-download-trimed-video.js code tested
4 function - 34 test cases
`npm test ffmpeg-download-trimed-video`             
#54
> Unit Test ffmpeg-download-trimed-video.js

- __tests__/backend/scripts/ffmpeg-download-stream.test.js
- __tests__/backend/scripts/ffmpeg-download-trimed-video.test.js
- backend/scripts/ffmpeg-download-stream.js
- client/scripts/videoPlayerButtons.js
- server.js
ffmpeg-download-stream.js code tested
9 function - 51 test cases
`npm test ffmpeg-download-stream` 
#54
> Unit Test ffmpeg-download-stream.js

- __tests__/backend/scripts/ffmpeg-download-image.test.js
- backend/scripts/ffmpeg-download-image.js
ffmpeg-download-image.js code tested
4 function - 25 test cases
`npm test ffmpeg-download-image`
#54
> Unit Test ffmpeg-download-image.js

- __tests__/backend/scripts/ffmpeg-download-compression.test.js
- __tests__/backend/scripts/ffmpeg-download-image.test.js
- backend/scripts/delete-data.js
- backend/scripts/ffmpeg-download-compression.js
- backend/scripts/ffmpeg-download-image.js
ffmpeg-download-compression.js code tested
9 function - 61 test cases
`npm test ffmpeg-download-compression`
updated ffmpeg-download-image.js test cases
4 function - 30 test cases
`npm test ffmpeg-download-image`
#54
> Unit Test ffmpeg-download-compression.js

- __tests__/backend/scripts/youtubedl-download-video.test.js
- backend/scripts/youtubedl-download-video.js
- server.js
youtubedl-download-video.js  code tested
2 function - 15 test cases
`npm test youtubedl-download-video `
#54
> Unit Test youtubedl-download-video.js 

- __tests__/backend/scripts/delete-data.test.js
- backend/scripts/delete-data.js
- backend/scripts/ffmpeg-download-compression.js
- server.js
refactored + tested delete-data.js code
13 function - 87 test cases
`npm test delete-data`
#54
> Unit Test delete-data.js

- __tests__/backend/scripts/ffmpeg-download-trimed-video.test.js
- __tests__/backend/scripts/ffmpeg-upload-video.test.js
- backend/scripts/ffmpeg-download-stream.js
- backend/scripts/ffmpeg-download-trimed-video.js
- backend/scripts/ffmpeg-download-video.js
- backend/scripts/ffmpeg-upload-video.js
ffmpeg-upload-video.js code tested
4 function - 29 test cases
`npm test ffmpeg-upload-video`
#54
> Unit Test ffmpeg-upload-video.js

- client/scripts/folder.js
- client/styles/video-folder-edit-settings.css
> Create folder interface - UI improvements

- __tests__/backend/scripts/youtubedl-download-video.test.js
- backend/scripts/youtubedl-download-video.js
- package-lock.json
- package.json
node-youtube-dl is deprecated switching to youtube-dl-exec.
Automatic will attempt to find the best quality video + youtube-dl will be updated to latest version.
[npm.im/youtube-dl](https://www.npmjs.com/package/youtube-dl)
[npm.im/youtube-dl-exec](https://www.npmjs.com/package/youtube-dl-exec)
closes #96
> youtube-dl -> youtube-dl-exec

- client/styles/index.css
> Fix: chooseVideoInputLabel padding under 379px

- client/scripts/basics.js
- client/scripts/currentVideoDownloads.js
- client/scripts/folder.js
- client/scripts/folderPath.js
- client/scripts/optionMenu.js
- client/scripts/search.js
- client/scripts/showAvailableVideos.js
Search functionalities in their own search.js file for better maintainability/readability
> Search functionalities -> search.js

- client/scripts/basics.js
- client/scripts/favicon.js
Favicon functionalities are inputted into their own file (favicon.js) for better maintainability/readability
> Favicon functionalities -> favicon.js 

- __tests__/backend/scripts/stream-video-image.test.js
- backend/scripts/stream-video-image.js
- server.js
stream-video-image.js  code tested
2 function - 13 test cases
`npm test stream-video-image`
#54
> Unit Test stream-video-image.js 

- __tests__/backend/scripts/ffmpeg-path.test.js
- __tests__/backend/scripts/ffmpeg-unfinished-videos.test.js
- __tests__/backend/scripts/ffmpeg-upload-video.test.js
- backend/scripts/ffmpeg-download-image.js
- backend/scripts/ffmpeg-path.js
- backend/scripts/ffmpeg-unfinished-videos.js
- backend/scripts/ffmpeg-upload-video.js
fmpeg-unfinished-videos.js code tested
6 function - 75 test cases
`npm test ffmpeg-unfinished-videos`
#54
> Unit Test ffmpeg-unfinished-videos.js

- __tests__/client/basics.test.js
- client/scripts/basics.js
- client/scripts/current-video-downloads.js
- client/scripts/download-trimed-video.js
- client/scripts/download-video.js
- client/scripts/folder-create.js
- client/scripts/folder-path.js
- client/scripts/index.js
- client/scripts/navigation-bar.js
- client/scripts/notify.js
- client/scripts/option-menu.js
- client/scripts/search.js
- client/scripts/show-available-videos.js
- client/scripts/upload-video.js
- client/scripts/video-player.js
reduced inputType, createLabel, createInput, createOption, createSection, createLink to one createElement function, Added isObject, isElement, made code easier to read and potentially more future proof.
All unit test's passed plus manually checked if the code is seposed to work the same.
> Refactored basics.js
